---
#Default data for each row
:default:
  :columns: &coldefault
    :editable: true
    :hidden: false

#:meta:
# this array used to set the listed keys to have a value of the column key for that column.
#    if :same_as_col_name = [:name, :index]
#    and there is a column[:address] entry
#    then column[:address][:name] and column[:address][:index] will both equal :address
#  :fill_col_names:
#    - :name
#    - :index

:grid: ~

:columns:
  :id:
    <<: *coldefault
    :hidden: true

  :name:
    <<: *coldefault
    :width: 300
    :header: "My Name!"
    :editrules:
      :required: true
